Full name: `Tan Ngoc Pham`    
Student ID: `19520925`

In [204]:
import numpy as np
import random

In [205]:
def initialize_population( num_individuals, num_variables ):
    """
    Khởi tạo quần thể gồm num_individuals cá thể. Mỗi cá thể có num_parameters biến.
    
    Arguments:
    num_individuals -- Số lượng cá thể
    num_variables -- Số lượng biến
    
    Returns:
    pop -- Ma trận (num_individuals, num_variables) chứa quần thể mới được khởi tạo ngẫu nhiên.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    pop = np.random.randint(2, size=(num_individuals, num_variables))
    ### DỪNG CODE TẠI ĐÂY ###
    
    return pop

In [206]:
pop = initialize_population(8, 4)
pop

array([[0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

In [207]:
def onemax( ind ):
    """
    Hàm đánh giá OneMax: Đếm số bit 1 trong chuỗi nhị phân (cá thể ind).
    
    Arguments:
    ind -- Cá thể cần được đánh giá.

    Returns:
    value -- Giá trị của cá thể ind.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ###     
    value = np.sum(ind)
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return value

In [208]:
onemax(pop[0])

1

In [209]:
def evaluate_population( pop ):
    """
    Hàm đánh giá tất cả cá thể trong quần thể.
    
    Arguments:
    pop -- Quàn thể cần được đánh giá.

    Returns:
    values -- Giá trị của tất cả các cá thể trong quần thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    values = [onemax(individual) for individual in pop]
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return values

In [210]:
pop_fitness = evaluate_population(pop)
pop_fitness

[1, 0, 2, 3, 4, 3, 2, 1]

In [211]:
def better_fitness( fitness_1, fitness_2, maximization=True ):
    """
    Hàm so sánh độ thích nghi của 2 cá thể.
    
    Arguments:
    fitness_1 -- Độ thích nghi của cá thể 1.
    fitness_2 -- Độ thích nghi của cá thể 2.
    maximization -- Biến boolean cho biết bài toán đang giải thuộc dạng tối đa hoá (mặc định) hay không
    
    Returns:
    True nếu fitness_1 tốt hơn fitness_2. Ngược lại, trả về False.
    """
    
    if maximization:
        if fitness_1 > fitness_2:
            return True
    else:
        if fitness_1 < fitness_2:
            return True
        
    return False

In [212]:
better_fitness(pop_fitness[6], pop_fitness[5])

False

In [213]:
def tournament_selection( pop, pop_fitness, selection_size, tournament_size):
    """
    Hàm chọn lọc cạnh tranh.
    
    Arguments:
    pop -- Quần thể để thực hiện phép chọn lọc.
    pop_fitness -- Mảng 1 chiều chứa giá trị (độ thích nghi) của từng cá thể trong quần thể.
    selection_size -- Số lượng cá thể sẽ được chọn.
    tournament_size -- Kích thước của tournament: Số lượng các cá thể được so sánh với nhau mỗi lần.
    
    Returns:
    selected_indices -- Chỉ số của những cá thể trong quần thể pop được chọn. Chỉ số có thể được lặp lại.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    indices = np.arange(num_individuals)
    selected_indices = []
    
    while len(selected_indices) < selection_size:
        # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể.
        np.random.shuffle(indices)
        pool = [pop[idx] for idx in indices]
        pool_fitness = [pop_fitness[idx] for idx in indices]
        
        for i in range(0, len(pop), tournament_size):
            max_index = np.argmax(pool_fitness[i : i + tournament_size + 1])
            selected_indices.append(i + max_index)
    ### DỪNG CODE TẠI ĐÂY ###
    
    return selected_indices

In [214]:
tournament_selection(pop, pop_fitness, len(pop), 4)

[0, 7, 3, 6, 2, 4, 4, 4]

In [215]:
def variation( pop ):
    """
    Hàm biến đổi tạo ra các cá thể con.
    
    Arguments:
    pop -- Quàn thể hiện tại.

    Returns:
    offspring -- Quần thể chứa các cá thể con được sinh ra.
    """  
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    indices = np.arange(num_individuals)
    # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể
    np.random.shuffle(indices)
    offspring = []
    
    for i in range(0, num_individuals, 2):
        idx1 = indices[i]
        idx2 = indices[i+1]
        offspring1 = list(pop[idx1])
        offspring2 = list(pop[idx2])
        
        # Cài đặt phép lai đồng nhất uniform crossover. 
        # Không cần cài đặt đột biến mutation.
        for i in range(len(offspring1)):
            tmp = random.uniform(0, 1)
            if tmp <= 0.5:
                offspring1[i], offspring2[i] = offspring2[i], offspring1[i]

        offspring.append(offspring1)
        offspring.append(offspring2)


    ### DỪNG CODE TẠI ĐÂY ###
    
    offspring = np.array(offspring)
    return offspring

In [216]:
variation(pop)

array([[0, 0, 0, 1],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 1],
       [1, 1, 1, 1]])

In [217]:
def popop(num_individuals, num_parameters, num_generations):
    """
    Hàm cài đặt thuật giải di truyền theo các bước P->O->(P+O)->P
    
    Arguments:
    num_individuals -- Số lượng cá thể trong quần thể.
    num_parameters -- Số lượng biến.
    num_generations -- Số thế hệ thuật toán sẽ chạy.

    Returns:
    In ra quần thể ở thế hệ cuối cùng và giá trị của từng cá thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    # Khởi tạo quần thể
    pop = initialize_population(num_individuals, num_parameters)
    pop_fitness = evaluate_population(pop)
    print("#Gen 0:")
    print(pop_fitness)
    
    # Sử dụng tournament_size 4 và selection_size là bằng kích thước quần thể
    selection_size = len(pop)
    tournament_size = 4

    for i in range(num_generations):
        # Tạo ra các cá thể con và đánh giá chúng
        offspring = variation(pop)
        offspring_fitness = evaluate_population(offspring)
        
        # Tạo ra quần thể pool gồm quần thể hiện tại pop và offspring
        pool = np.vstack((pop,offspring))
        pool_fitness = np.hstack((pop_fitness, offspring_fitness))

        # Thực hiện tournament selection trên quần thể pool 
        pool_indices = tournament_selection(pop, pop_fitness, selection_size, tournament_size)

        # Thay thế quần thể hiện tại bằng những cá thể được chọn ra từ pool.
        pop = pool[pool_indices, :]
        pop_fitness = pool_fitness[pool_indices]
        print("#Gen {}:".format(i+1))
        print(pop_fitness)

    ### DỪNG CODE TẠI ĐÂY ###
    print("#Result:")
    print(pop)
    print(pop_fitness)

In [221]:
# Trường hợp kích thước quần thể là 4
# np.random.seed(58)
num_parameters = 20
num_individuals = 4
num_generations = 10
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[8, 11, 8, 10]
#Gen 1:
[ 8 10  8 10]
#Gen 2:
[10  8  8  8]
#Gen 3:
[8 8 8 8]
#Gen 4:
[8 8 8 8]
#Gen 5:
[8 8 8 8]
#Gen 6:
[8 8 8 8]
#Gen 7:
[8 8 8 8]
#Gen 8:
[8 8 8 8]
#Gen 9:
[8 8 8 8]
#Gen 10:
[8 8 8 8]
#Result:
[[1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0]
 [1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0]
 [1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0]
 [1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0]]
[8 8 8 8]


In [234]:
# Trường hợp kích thước quần thể là 8
np.random.seed(44)
num_parameters = 4
num_individuals = 8
num_generations = 10
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[3, 2, 2, 3, 4, 2, 3, 2]
#Gen 1:
[2 4 3 4 2 4 2 2]
#Gen 2:
[4 2 4 2 2 4 3 2]
#Gen 3:
[2 4 4 2 2 4 4 2]
#Gen 4:
[4 2 4 4 2 4 2 2]
#Gen 5:
[4 4 2 2 4 2 4 4]
#Gen 6:
[4 4 4 4 4 4 4 4]
#Gen 7:
[4 4 4 4 4 4 4 4]
#Gen 8:
[4 4 4 4 4 4 4 4]
#Gen 9:
[4 4 4 4 4 4 4 4]
#Gen 10:
[4 4 4 4 4 4 4 4]
#Result:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[4 4 4 4 4 4 4 4]


In [242]:
# Trường hợp kích thước quần thể là 16
np.random.seed(59)
num_parameters = 20
num_individuals = 16
num_generations = 10
popop(num_individuals, num_parameters, num_generations)

#Gen 0:
[14, 6, 13, 11, 10, 13, 8, 10, 11, 11, 11, 10, 11, 8, 8, 11]
#Gen 1:
[10 10 10 11 13  8 11 11  6  8 11  8 13  8 11  8]
#Gen 2:
[10  8  8 13 10  8 13 13 10 11  6 11 10 13  8  8]
#Gen 3:
[10 10  6 10  8 13  6 13 10 13  6 13  8  8 11 10]
#Gen 4:
[10 13 13 11  8  8 13 11 10  6 13  8 10  6 13 11]
#Gen 5:
[13 13 13 10 13 10 10 10 13  8  6 11 13  8 10 13]
#Gen 6:
[13 13 13  8 13 13 13 13 10 13 11 13 13 10 13 10]
#Gen 7:
[13 13 10 13 13 13 13 10 13 13 10 13 13 13 10 10]
#Gen 8:
[13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13]
#Gen 9:
[13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13]
#Gen 10:
[13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13]
#Result:
[[1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 